"""Fix one-to-one User-Portfolio relationship

Revision ID: 1dbc24a703d5
Revises: 55099686a1a3
Create Date: 2025-05-20 23:56:21.215489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbc24a703d5'
down_revision = '55099686a1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('portfolio_fk', type_='foreignkey')
        batch_op.drop_column('portfolio_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('portfolio_fk', 'portfolio', ['portfolio_id'], ['id'])

    # ### end Alembic commands ###
