"""Fix user-portfolio one-to-one relationship

Revision ID: 55099686a1a3
Revises: 
Create Date: 2025-05-20 21:28:13.565341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55099686a1a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('portfolio_fk', 'portfolio', ['portfolio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('portfolio_id')

    # ### end Alembic commands ###
